COUNTRIES_TO_REMOVE = [
    'ASEAN (Ember)',
    'Africa',
    'Africa (EI)',
    'Africa (Ember)',
    'Africa (Shift)',
    'Asia',
    'Asia & Oceania (EIA)',
    'Asia (Ember)',
    'Asia Pacific (EI)',
    'Asia and Oceania (Shift)',
    'Australia and New Zealand (EIA)',
    'CIS (EI)',
    'Central & South America (EIA)',
    'South America',
    'South and Central America (EI)',
    'Central America (EI)',
    'Central and South America (Shift)',
    'EU28 (Shift)',
    'East Germany (EIA)',
    'Eastern Africa (EI)',
    'Eurasia (EIA)',
    'Eurasia (Shift)',
    'Europe',
    'Europe (EI)',
    'Europe (Ember)',
    'Europe (Shift)',
    'European Union (27)',
    'European Union (EIA)',
    'G20 (Ember)',
    'G7 (Ember)',
    'Hawaiian Trade Zone (EIA)',
    'High-income countries',
    'IEO - Africa (EIA)',
    'IEO - Middle East (EIA)',
    'IEO OECD - Europe (EIA)',
    'Latin America and Caribbean (Ember)',
    'Low-income countries',
    'Lower-middle-income countries',
    'Mexico, Chile, and other OECD Americas (EIA)',
    'Middle Africa (EI)',
    'Middle East (EI)',
    'Middle East (EIA)',
    'Middle East (Ember)',
    'Middle East (Shift)',
    'Non-OECD (EI)',
    'Non-OECD (EIA)',
    'Non-OPEC (EI)',
    'Non-OPEC (EIA)',
    'North America',
    'North America (EI)',
    'North America (Ember)',
    'North America (Shift)',
    'OECD (EI)',
    'OECD (EIA)',
    'OECD (Ember)',
    'OECD (Shift)',
    'OECD - Asia And Oceania (EIA)',
    'OECD - Europe (EIA)',
    'OECD - North America (EIA)',
    'OPEC (EI)',
    'OPEC (EIA)',
    'OPEC (Shift)',
    'OPEC - Africa (EIA)',
    'OPEC - South America (EIA)',
    'Oceania',
    'Oceania (Ember)',
    'Other Non-OECD - America (EIA)',
    'Other Non-OECD - Asia (EIA)',
    'Other Non-OECD - Europe and Eurasia (EIA)',
    'U.S. Pacific Islands (EIA)',
    'U.S. Territories (EIA)',
    'USSR',
    'United States Pacific Islands (Shift)',
    'United States Territories (Shift)',
    'United States Virgin Islands',
    'Persian Gulf (EIA)',
    'Persian Gulf (Shift)',
    'South Korea and other OECD Asia (EIA)',
    'Upper-middle-income countries',
    'Wake Island (EIA)',
    'Wake Island (Shift)',
    'West Germany (EIA)',
    'Western Africa (EI)',
    'World',
    'Yugoslavia'
]

RENEWABLE_COLUMNS = [
    'country', 'year', 'iso_code', 'population', 'gdp',
    'renewables_cons_change_pct', 'renewables_cons_change_twh', 'renewables_consumption',
    'renewables_elec_per_capita', 'renewables_electricity', 'renewables_energy_per_capita',
    'renewables_share_elec', 'renewables_share_energy', 'solar_cons_change_pct',
    'solar_cons_change_twh', 'solar_consumption', 'solar_elec_per_capita', 'solar_electricity',
    'solar_energy_per_capita', 'solar_share_elec', 'solar_share_energy', 'wind_cons_change_pct',
    'wind_cons_change_twh', 'wind_consumption', 'wind_elec_per_capita', 'wind_electricity',
    'wind_energy_per_capita', 'wind_share_elec', 'wind_share_energy', 'hydro_cons_change_pct',
    'hydro_cons_change_twh', 'hydro_consumption', 'hydro_elec_per_capita', 'hydro_electricity',
    'hydro_energy_per_capita', 'hydro_share_elec', 'hydro_share_energy',
    'other_renewable_consumption', 'other_renewable_electricity',
    'other_renewable_exc_biofuel_electricity', 'other_renewables_cons_change_pct',
    'other_renewables_cons_change_twh', 'other_renewables_elec_per_capita',
    'other_renewables_elec_per_capita_exc_biofuel', 'other_renewables_energy_per_capita',
    'other_renewables_share_elec', 'other_renewables_share_elec_exc_biofuel',
    'other_renewables_share_energy', 'electricity_generation'
]

NON_RENEWABLE_COLUMNS = [
    'country', 'year', 'iso_code', 'population', 'gdp',
    'fossil_cons_change_pct', 'fossil_cons_change_twh', 'fossil_elec_per_capita',
    'fossil_electricity', 'fossil_energy_per_capita', 'fossil_fuel_consumption',
    'fossil_share_elec', 'fossil_share_energy', 'coal_cons_change_pct',
    'coal_cons_change_twh', 'coal_cons_per_capita', 'coal_consumption',
    'coal_elec_per_capita', 'coal_electricity', 'coal_prod_change_pct',
    'coal_prod_change_twh', 'coal_prod_per_capita', 'coal_production',
    'coal_share_elec', 'coal_share_energy', 'oil_cons_change_pct', 'oil_cons_change_twh',
    'oil_consumption', 'oil_elec_per_capita', 'oil_electricity', 'oil_energy_per_capita',
    'oil_prod_change_pct', 'oil_prod_change_twh', 'oil_prod_per_capita', 'oil_production',
    'oil_share_elec', 'oil_share_energy', 'gas_cons_change_pct', 'gas_cons_change_twh',
    'gas_consumption', 'gas_elec_per_capita', 'gas_electricity', 'gas_energy_per_capita',
    'gas_prod_change_pct', 'gas_prod_change_twh', 'gas_prod_per_capita', 'gas_production',
    'gas_share_elec', 'gas_share_energy', 'nuclear_cons_change_pct', 'nuclear_cons_change_twh',
    'nuclear_consumption', 'nuclear_elec_per_capita', 'nuclear_electricity',
    'nuclear_energy_per_capita', 'nuclear_share_elec', 'nuclear_share_energy', 'electricity_generation', 'renewables_electricity'
]
